### ISSUE TITLE
Allow single-file input for converters

### ISSUE THREAD

**Issue by neumannm** [openminted/uc-tdm-socialsciences#10]
Currently it's only possible to specifiy a directory where PDFs/XML files reside. It should also be possible to provide a single file to be converted.

**Comment by neumannm** [comment]
What about PdfxXmlToXmiConverter, this currently only supports input directories right @maxxkia ?

**Comment by reckart** [comment]
DKPro Core readers usually allow PARAM_SOURCE_LOCATION to be either a directory/pattern or a single file, e.g.

```
PARAM_SOURCE_LOCATION, "some/folder/**/*.txt"
```

or

```
PARAM_SOURCE_LOCATION, "some/folder/file.txt"
```

**Comment by neumannm** [comment]
Sure, I'm just referring to our surrounding code. It relies on user input of the input directory and I'm not quite sure what happens if the user inputs the path to a single input file directly.
