### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by neumannm** [openminted/uc-tdm-socialsciences#20]
Here's what's expected to be in the documentation:

"1) An initial page to introduce the application and it’s functionality.  2) A separate page for each ‘data processing scenario’ from the Application Design report for that application, outlining the execution of the scenario from the user’s perspective."

So our tasks are:

- [x] Write introduction
- [x] look up the 'data processing scenarios' from the Application Design Report
- [x] create a separate page for each of those scenarios (that applied to this release) and explain how our application works

**Comment by maxxkia** [comment]
I can take care of the data harmonization step.

**Comment by neumannm** [comment]
Ok cool, I will take care of the ner part then.

**Comment by maxxkia** [comment]
You can find the introduction section in the following file
```
ss-doc/src/main/asciidoc/user-guide/introduction.adoc
```
and component's descriptions here
```
ss-doc/src/main/asciidoc/user-guide/components.adoc
```

If documentation for the components gets too long we can split into individual files for each module.

**Comment by maxxkia** [comment]
You can also see that these are included in this file:
```
ss-doc/src/main/asciidoc/user-guide.adoc
```
which creates the complete documentation.
Every time a build is triggered an html documentation is created. There's also a block inside `ss-doc/pom.xml` which triggers creation of pdf documentation (if uncommented).

**Comment by maxxkia** [comment]
@neumannm As a quick Asciidoc reference you can refer to
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

**Comment by neumannm** [comment]
Thanks for all the hints, too kind of you. :)

**Comment by maxxkia** [comment]
no problem ;)

**Comment by neumannm** [comment]
I think we should agree on a style of writing so that our documentation is consistent in style. I started off with a more personal style, like "you can do this and that". But we could also use a more formal style.

**Comment by maxxkia** [comment]
Sure. I think your current style is fine. We can review the whole documentation at the end to spot changes in style/tone.
