### ISSUE TITLE
Use args4j in stanfordNER pipeline

### ISSUE THREAD

**Issue by maxxkia** [openminted/uc-tdm-socialsciences#24]
Use args4j library in StanfordNER pipeline class to handle program input arguments.

**Comment by reckart** [comment]
I'd rather recommend args4j. commons-cli is a bit ancient and afaik commons-cli2 hasn't been released for years.

**Comment by reckart** [comment]
http://args4j.kohsuke.org

**Comment by maxxkia** [comment]
Thanks for your quick comment :)
I'll have look at args4j.
