### ISSUE TITLE
Dictionary files for PdfxXmlToXmiConverter can't be accessed in jar file

### ISSUE THREAD

**Issue by maxxkia** [openminted/uc-tdm-socialsciences#30]
English and German dictionary files required for PdfxXmlToXmiConverter can't be accessed in jar file since they are referenced as classpath files. Files should be provided separately and given as input parameter to the component.

**Comment by neumannm** [comment]
I also just noticed that we have two german dictionary files in there. I don't remember why. I think it's sufficient to keep the one with more entries.

Do you really want the user to specify a dictionary file?

**Comment by maxxkia** [comment]
Yes I will remove the smaller German dictionary file.

I will need to add a parameter for application home directory, so the program can find the required files (the dictionaries) and pass them to hyphenationRemover. HyphenationRemover component expects a file path however files inside a jar can't be opened like regular files (you can just open an input stream from them) this is why hyphenationRemover can't access the files like this (only when run from jar, in IDE files are loaded from classpath directory not jar).
