### ISSUE TITLE
Log4j error in pdfx-pipeline

### ISSUE THREAD

**Issue by neumannm** [openminted/uc-tdm-socialsciences#32]
I noticed that Log4j outputs the following error when running the pdfx to xmi pipeline:

 ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

I can't see a difference in configuration to the other modules, where this error doesn't appear.

**Comment by maxxkia** [comment]
This error happened because I switched to the newer version of log4j in ss-common module. This new version requires a new config file named as `log4j2.xml`.
