### ISSUE TITLE
Remove application.properties file and replace it with application.properties.TEMPLATE

### ISSUE THREAD

**Issue by maxxkia** [openminted/uc-tdm-socialsciences#4]
`application.properties` should be added to ignored files and instead a `application.properties.TEMPLATE` file should be created which will be initialized by each user according to their environment settings.

**Comment by neumannm** [comment]
I agree. We should also provide such a template file for the kb-preparation module (where application.properties is already ignored). Or maybe use a _single_ properties file for all modules?

**Comment by maxxkia** [comment]
Let's keep separate `application.properties` files for each module for the moment.
