### ISSUE TITLE
PdfxXmlReaderTest.testReadArticle1WithAppendNewLine() sometimes fails

### ISSUE THREAD

**Issue by maxxkia** [openminted/uc-tdm-socialsciences#6]
This test fails on Linux machine and passes on a Windows machine. Should figure out why this is happening.

**Comment by maxxkia** [comment]
@reckart could you also test this on your machine?

p.s. we added .gitattributes, so I suppose this is not a problem with inconsistent line endings.

**Comment by reckart** [comment]
@maxxkia the code as it is in the repo doesn't fail its test for me. But mind that your .gitattributes file only declares `xml` files as text files (subject to line-ending conversion). But there test reference files in the repo have the ending ".xml.dump". I assume they are presently still treated as binary files by git (not subject to line-ending conversion).

**Comment by neumannm** [comment]
@reckart Thanks for the hint.
@maxxkia I just pushed the change of the .gitattributes file.

**Comment by maxxkia** [comment]
Now it works for me as well with the latest commit
https://github.com/openminted/uc-tdm-socialsciences/commit/334524ef8413dcf8f0f854a9711c3b5baf2e3a9c
