### ISSUE TITLE
Don't commit resources for tests

### ISSUE THREAD

**Issue by neumannm** [openminted/uc-tdm-socialsciences#7]
I think we should put all resources under `src/test/resources` in `.gitignore` so that they are not commited and pushed. So the user has to put pdf files or whatever is needed in this folder locally before running any tests. I already did this in the kb-preparation module.

**Comment by reckart** [comment]
Tests should be able to run on jenkins. Minimal test files should be included in the repository. src/test/resources should not be ignored.

**Comment by reckart** [comment]
If you use test files not created by yourself, please add a README file explaining from there the files were obtained and under which licenses they are.

**Comment by maxxkia** [comment]
I agree with Richard. This is in contradiction with the concept of tests. Tests and the test resources should be carefully designed/chosen so that if an unsafe change is applied to code, the tests should break and they alert for where to look for problems.

**Comment by maxxkia** [comment]
On the other hand, this might work for some of the tests but not for those that require checking against a verified-copy (e.g. X.dump). X.dump resources should be left **untouched** unless the author intentionally changes the internal structure of CAS and that is the time they have to be recreated to work with the current implementation (like serealization output).

**Comment by neumannm** [comment]
Ok I see your points. I just wasn't sure about the pdfs because they are from an open access repository, but does this mean that we can redistribute them publically on github?

**Comment by reckart** [comment]
@neumannm you need to check the conditions of the open access repository. Hopefully redistribution is allowed. Otherwise, you could just create a PDF document from some Latex yourself. In that way you can closely control what oddities the file contains and whether or not they are properly recognized.

**Comment by maxxkia** [comment]
The license notice (e.g. at [2819.pdf](http://www.ssoar.info/ssoar/handle/document/2819)) says:
> Deposit Licence - No Redistribution, No Modifications 

I think this doesn't allow distributing the PDFs but I'm not sure how it applies to processed XMLs.

**Comment by maxxkia** [comment]
I think `No Modifications` also covers XMLs in our case?! so we can't even distribute the processed XML?

**Comment by reckart** [comment]
Probably not.

**Comment by reckart** [comment]
So I think going with hand-crafted PDFs for testing is probably the way to go... or use PDFs from other sources (e.g. LREC which is CC-BY).

**Comment by neumannm** [comment]
For now I added some pdfs from LREC proceedings and removed the other resources.
