### ISSUE TITLE
Don't process pdf when overwriteOutput=false and output file already present

### ISSUE THREAD

**Issue by neumannm** [openminted/uc-tdm-socialsciences#9]
Currently, the variable `overwriteOutput` is only used in the `writeToFile` method. But if `overwriteOutput` is set to `false`, there is no point in even starting the processing if the output file is already present. So it should be checked first if this is the case and start processing only if
- `overwriteOutput` is set to `True`
- the output file is not already there

**Comment by maxxkia** [comment]
Right, thanks for creating the issue. I had added this as a todo in the code but forgot to create the issue.
